### ISSUE TITLE
csrf_token() throws undefined in testing while {{ form.csrf_token }} passes

### ISSUE THREAD

**Issue by gobijan** [lepture/flask-wtf#107]
Hi I want to unittest a manual form that uses csrf_token():
<input id="csrf_token" name="csrf_token" type="hidden" value="{{ csrf_token() }}">

It throws UndefinedError: 'csrf_token' is undefined.

When I have a form object and I invoke {{ form.csrf_token }} in testing it works.
I expect the manual use of csrf_token() in unittests not to break the tests because of undefined. 

Am I doing something wrong or is this a bug?

THX and Regrads

**Comment by raf1hh** [comment]
I have run into this too. I did a search on the whole code base for the project and csrf_token() method is not defined anywhere. I ended up grabbing the token from the session object: session['csrf']

**Comment by 2ni** [comment]
http://stackoverflow.com/questions/31888316/how-to-use-flask-wtforms-csrf-protection-with-ajax#answer-31888868

You need to load CsrfProtect(app) or:
csrf = CSRFProtect()

def create_app():
    app = Flask(__name__)
    csrf.init_app(app)

then you can access csrf_token()
