### ISSUE TITLE
Flask-Restful POST fails due CSRF protection of Flask-WTF

### ISSUE THREAD

**Issue by houmie** [lepture/flask-wtf#111]
I am using normal flask web + flask-restful. So I need CSRF protection for web but not for REST.

The moment I enable `CsrfProtect(app)` of flask-wtf, all my post unit tests for flask-restful return a 400.

Is there a way to disable CSRF protection for REST services since they are coming from mobile handsets without session handling anyway, hence CSRF wouldn't make much sense.

This is how I test it:

```
rv = self.client.post('api/v1.0/verify-email', environ_base={'REMOTE_ADDR': '127.0.0.1'}, headers={'Content-Type':'application/json'}, data=json.dumps(data))
self.check_content_type(rv.headers)
eq_(rv.status_code, 412)
```

I know there is a way to exempt it:
https://flask-wtf.readthedocs.org/en/latest/api.html#flask_wtf.csrf.CsrfProtect.exempt

But this approach doesn't work with Flask-Restful:

```
api = Api(app)
api.add_resource(EmailVerificationAPI, '/api/v1.0/verify-email') 
```

Many Thanks
Hooman

**Comment by paleomedia** [comment]
@lepture can you give an example of where to add csrf.exempt(account_blueprint)? I have an apiModule blueprint with all of my API methods and want to exempt them all ...

**Comment by davidism** [comment]
@paleomedia call it when you have access to both `csrf` and `blueprint`.  Around where you register the blueprint seems like a good place as any.

**Comment by weihaixiaoseu** [comment]
I need some help please :( . I am using Flask-JWT and CSRFProtect together, but I fail to access /auth to get the token, which responsed with "The CSRF token is missing" and status 400. Even though I've tried to exempt the api blueprint. What should I do? Thank you very much!

**Comment by lepture** [comment]
@weihaixiaoseu Please read the documentation: https://flask-wtf.readthedocs.io/en/stable/csrf.html#exclude-views-from-protection

BTW. Don't ask unrelated questions in other issues.
