### ISSUE TITLE
Access CsrfProtect instance from Blueprints.

### ISSUE THREAD

**Issue by nobane** [lepture/flask-wtf#119]
I am wanting to exempt a route in my blueprint, but requires importing the CsrfProtect instance from my main module where Flask is also instantiated and the Blueprint is imported into. I end up with a circular import (main module imports Blueprint, Blueprint imports from main module to get csrf instance, circular import happens/error).

**Comment by andreibancioiu** [comment]
A possible workaround:

```
csrf = CSRFProtect(app)
csrf.exempt("your_package.your_module.your_view_function")
```
