### ISSUE TITLE
QuerySelectField and json payload

### ISSUE THREAD

**Issue by debrice** [lepture/flask-wtf#123]
Hi,

When sending an application/json payload, form.__init__ converts it to a json dict. QuerySelectField is always converting pk into str/unicode, the issue is that some new framework tend to submit models (like angularjs) as a json payload, the common pk still being an integer/autoincrement, the validation always fails as the pk (type int) is now compared with a type str.

Where the conversion of the pk to str occurs
https://github.com/wtforms/wtforms/blob/master/wtforms/ext/sqlalchemy/fields.py#L100

Where Flask-WTF do the magic of converting the payload to a json object
https://github.com/lepture/flask-wtf/blob/master/flask_wtf/form.py#L78

I made a request to WTForms https://github.com/wtforms/wtforms/pull/79 but got closed for legitimate reason I think.

**Comment by davidism** [comment]
This is an issue either with how `QuerySelectField` validates, or how the data is sent.  Flask-WTF isn't doing anything excpet loading the data.
