### ISSUE TITLE
is_submitted for multiple forms with prefix

### ISSUE THREAD

**Issue by snc-tolksdorf** [lepture/flask-wtf#140]
flask_wtf/form.py :: Form

should it be like this?

    class Multiform(Form):
        def __init__(self, *args, **kwargs):
            self.prefix = ""
            if "prefix" in kwargs:
                self.prefix = kwargs["prefix"]
            super(Multiform, self).__init__(*args, **kwargs)
    
        def is_submitted(self):
            if request:
                for value in request.values:
                    if value.startswith(self.prefix):
                        return True
            return False

**Comment by willcharlton** [comment]
I like this idea. But, where does `request` come from in the overridden `is_submitted` function?

**Comment by Xender** [comment]
@willcharlton Probably directly from Flask. Note that `is_submitted` is Flask-WTF-specific - this method simply does not exist in original WTForms's `Form`.

**Comment by willcharlton** [comment]
Yep. I got this working. Missing the import from flask was all.

```
# forms.py
from flask import request

class Multiform(Form):
	def __init__(self, *args, **kwargs):
		self.prefix = ""
		if "prefix" in kwargs:
			self.prefix = kwargs["prefix"]
		super(Multiform, self).__init__(*args, **kwargs)

	def is_submitted(self):
		if request:
			for value in request.values:
				if value.startswith(self.prefix):
					return True
		return False

class Form1(Multiform):
	def __init__(self, *args, **kwargs):
		MultiConfirm.__init__(self, *args, **kwargs)
class Form2(Multiform):
	def __init__(self, *args, **kwargs):
		MultiConfirm.__init__(self, *args, **kwargs)
```

I've confirmed this works when you instantiate your forms with a `prefix` arg.

```
# views.py
# all imports and views...

@app.route('/mine'):
	form1 = Form1(prefix='form1')
	form2 = Form2(prefix='form2')

	if form1.validate_on_submit(): # pylint: disable=I0011,E1101
		return redirect(request.url)
	if form2.validate_on_submit(): # pylint: disable=I0011,E1101
		return redirect(request.url)
```

Having this in the route/view before any checks like `request.method == 'POST` works well for my use-case.
