### ISSUE TITLE
Allow CsrfProtect(blueprint)

### ISSUE THREAD

**Issue by fayazkhan** [lepture/flask-wtf#144]
Selectively enforcing CSRF is preferable rather than csrf.exempt(blueprint) IMO.
Is it doable? (I was looking into it and was lost at what to do with the config variables.) Does it make sense? Is #111 really the "obvious way to do it"? (I'm not Dutch)

**Comment by lepture** [comment]
With this change https://github.com/lepture/flask-wtf/commit/e85808b9e7432f4e5b782032e32ad8cc3939e7d1

You can set WTF_CSRF_CHECK_DEFAULT to False, and protect a single blueprint with:

```python
csrf = CsrfProtect(app)

some_blueprint.before_request(csrf.protect)
```

**Comment by fayazkhan** [comment]
That's good enough I guess.
