### ISSUE TITLE
Feature request - Captcha support

### ISSUE THREAD

**Issue by kristen1980** [lepture/flask-wtf#151]
We've been using flask-wtf with recaptcha but would like to have something that isn't dependent on a 3rd party service. Integrating with something like flask-captcha would be great if anyone has the time.

**Comment by davidism** [comment]
If someone finds an up-to-date offline captcha library that supports the versions of Python that Flask-WTF supports and wants to add a description and link to the docs, that's welcome.  Closing this as we do not plan on adding direct support for more captcha systems.
