### ISSUE TITLE
Use new reCaptcha api

### ISSUE THREAD

**Issue by git-commit** [lepture/flask-wtf#163]
Google recently released an update to their reCaptcha service.
The old api remains working, but it would be nice to use the new api instead.

I already did some work on this (#164). 

See: https://developers.google.com/recaptcha/docs/

**Comment by dmnBrest** [comment]
Is there any solution to enable new recaptcha feature "I'm not a robot" in flask-wtf? Is it related to new api version?
![957f0d96ac1a2cb2101cc3b2fe1cc32652236129](https://cloud.githubusercontent.com/assets/7594309/5792416/33fe477e-9f28-11e4-945b-11e90d576d7c.gif)

**Comment by git-commit** [comment]
Yes this is how recaptcha looks when used with the new api.
You can checkout the pull request I mentioned in my starting post which is using the new api.
Report back if everything still works for you.

**Comment by lepture** [comment]
released in https://pypi.python.org/pypi/Flask-WTF/0.11
