### ISSUE TITLE
Cannot set language for RECAPTCHA

### ISSUE THREAD

**Issue by truff77** [lepture/flask-wtf#166]
Hi, I'm trying to set the language for the RECAPTCHA widget but it looks like it does not work by using the following:
RECAPTCHA_OPTIONS = { lang: 'fr' }

Any hint please ?

**Comment by lepture** [comment]
@truff77 We have just upgraded reCAPTCHA to the new reCAPTCHA. The `RECAPTCHA_OPTIONS` doesn't working yet.

**Comment by lepture** [comment]
@truff77 updated in https://github.com/lepture/flask-wtf/commit/65ab8c316d2e7e9f1ea30c60dc567bd76f2a5796

```
RECAPTCHA_PARAMETERS = {'hl': 'zh'}
```

**Comment by truff77** [comment]
Hi Lepture, thanks for correcting this. I'll give a try soon.

**Comment by lepture** [comment]
@truff77 Use the source code in Git. It hasn't been released.

**Comment by truff77** [comment]
@lepture Yes I'll use 65ab8c3 as you informed.

**Comment by truff77** [comment]
@lepture It work great with new Recaptcha. I did not even had to use the options as it is getting automatically to the language set into the browser.

**Comment by lepture** [comment]
@truff77 Yes. The `option` is useful when you want to force to a certain language.
