### ISSUE TITLE
Current Version?

### ISSUE THREAD

**Issue by tofias** [lepture/flask-wtf#171]
From the documentation: "The current version of Flask-WTF is 0.9.5." 

I was under the impression this implied "current stable version." However, I had trouble with the CSRF-based AJAX features in 0.9.5 (even though the documentation reports them as available since 0.9.0). After bumping to the latest version, I find all the lovely things in app.jinja_env.globals as expected. So maybe it would be useful to increment this *current version* number?

**Comment by rsyring** [comment]
I saw this in the docs too.  My recommendation would be to just remove this sentance or point them to PyPI for the latest version.

**Comment by tofias** [comment]
That would work, but there is a version variable in `~/docs/conf.py`. It just needs to be bumped.

**Comment by lepture** [comment]
Removed current version section.
