### ISSUE TITLE
How do form instances know about user-submitted data?

### ISSUE THREAD

**Issue by DanielSank** [lepture/flask-wtf#172]
Here's a bit of code from the quickstart documentation:

```python
@app.route('/submit', methods=('GET', 'POST'))
def submit():
    form = MyForm()
    if form.validate_on_submit():
        return redirect('/success')
    return render_template('submit.html', form=form)
```

I am puzzled by this code. when we do `form = MyForm()` we are constructing a new object. How does the `validate_on_submit()` method have access to the data submitted by the user?

Just below the code there is this tantalizing statement:
> Note that you don’t have to pass request.form to Flask-WTF; it will load automatically. And the convenience validate_on_submit will check if it is a POST request and if it is valid.

How is this possible? Is there some thread-local trickery here?

**Comment by davidism** [comment]
If no data is explicitly passed in, it tries `request.form` automatically.

https://github.com/lepture/flask-wtf/blob/master/flask_wtf/form.py#L72

**Comment by DanielSank** [comment]
Ah, I see how this work now. Thank you. Flask's method of achieving thread safety seems have very strange consequences in how code is written!
