### ISSUE TITLE
Can't disable csrf per form

### ISSUE THREAD

**Issue by italomaia** [lepture/flask-wtf#173]
Just tried something like this:
```
class MyForm(Form):
    class Meta:
        csrf = False
```

And a csrf not present error was thrown. I need to disable csrf so that my GET form can be accessed from outside with query parameters directly.

**Comment by lepture** [comment]
@italomaia MyForm(csrf_enabled=False)

**Comment by italomaia** [comment]
I'll try that but, shouldn't the example above do the same?

**Comment by TronPaul** [comment]
I'm having this issue myself, though I'm not sure if it's a different manifestation. It seems to be because `wtforms.csrf.from.SecureForm` always adds a csrf token field which will then be validated when `validate_on_submit()` is called. Not sure how to fix this.

**Comment by lepture** [comment]
Maybe it is because the version of WTForms.

**Comment by davidism** [comment]
Using CSRF is already [documented](http://flask-wtf.readthedocs.io/en/latest/form.html#module-flask_wtf).  Flask-WTF uses the (soon to be deprecated) `SecureForm` from WTForms, not the new `Meta` implementation.  See #216.
