### ISSUE TITLE
Unable to selectively turn on _csrf_protect()

### ISSUE THREAD

**Issue by AngledLuffa** [lepture/flask-wtf#179]
The documentation for csrf protection says the config option WTF_CSRF_CHECK_DEFAULT will turn off the default csrf checking.

https://flask-wtf.readthedocs.org/en/latest/csrf.html

However, the option WTF_CSRF_CHECK_DEFAULT is not checked anywhere in the csrf code:

```
MacBook-Pro:/usr/local/lib/python2.7/site-packages/flask_wtf$ find . -name "*py" -exec grep -H "WTF_CSRF_CHECK_DEFAULT" "{}" ";"
MacBook-Pro:/usr/local/lib/python2.7/site-packages/flask_wtf$
```

The documentation further says that you can then call csrf.protect() to check the protection on a page once the default checking has been turned off.  However, csrf.protect() is not implemented.  The only method available in the CsrfProtect class is _csrf_protect, with no way to call that method directly.

**Comment by AngledLuffa** [comment]
This is with version 0.11 of flask-wtf

**Comment by lepture** [comment]
https://github.com/lepture/flask-wtf/blob/master/flask_wtf/csrf.py#L159

**Comment by lepture** [comment]
@AngledLuffa OMG. I'll need to release another version.

**Comment by AngledLuffa** [comment]
That would be very appreciated, thanks :)

In the meantime we are using a git checkout, so for us personally there is no rush

**Comment by michael-kehoe** [comment]
It would be nice if the protect() method was also a decorator. It would be useful to selectively turn on protection and by default leave it off using  "WTF_CSRF_CHECK_DEFAULT"
