### ISSUE TITLE
is_submitted with multiple forms?

### ISSUE THREAD

**Issue by harrisonmetz** [lepture/flask-wtf#182]
I'm having an issue (maybe related to #140 ) but I'll phrase it as a question.

If I have multiple forms on the same page, how does flask-wtf know which form was submitted and which one wasn't? Basically, I get an error that the form that wasn't submitted complains about a missing CSRF (as the CSRF for that form never came across because it wasn't submitted). While validate_on_submit() doesn't run true, is_submitted() returns true. This leads to two problems:

1) It tries to validate a form that wasn't submitted (thus complaining about missing fields)
2) If a form is populated with an initial object, it no longer displays that data as the form _thinks_ it was submitted when it wasn't.

I think a possible solution would be to make the is_submitted() actually know if a form was submitted by checking more than just if the request has a POST or PUT. It could check to make sure that the submit field was present, or even add a hidden field which a unique name and see if that came across.

**Comment by cureshot** [comment]
Is there a fix or workaround for this issue? (or how did you manage the problem? )
I have stumbled on the exact same problem for 2 days!

**Comment by lepture** [comment]
The best solution is **one form one action URL**. But if you must submit two forms to one action URLs, you should detect which form are you using yourself. e.g.

Here is an example:

```html
<form>
  <input type="hidden" name="form-name" value="form1">
</form>

<form>
  <input type="hidden" name="form-name" value="form2">
</form>
```

```python
def some_view():
    form1 = SomeForm()
    form2 = AnotherForm()
    if request.method == 'POST':
        form_name = request.form['form-name']
        if form_name == 'form1':
            form1.validate()
            ...
    ...
```

**Comment by Xender** [comment]
@harrisonmetz - I have a use case for multiple forms in a single view too.
I am working on a solution that would be elegant and correct if possible.
Probably going to end up as external library subclassing over flask_wtf.Form.
I will give update on my progress.

If you already have a solution that would require less boilerplate code placed directly in the view than @lepture's, I'd be thankful if you could share it somewhere. :)

**Comment by chris2513** [comment]
Here's my solution for having two forms on one page.

`def some_view():
    form1 = SomeForm()
    form2 = AnotherForm()
    submitted = form1 if form1.field.data else form2
    if(submitted.validate_on_submit()):
        # do some stuff here`

Hope this is what you're looking for.
