### ISSUE TITLE
Not EqualTo

### ISSUE THREAD

**Issue by Garito** [lepture/flask-wtf#184]
Hi!
How can I create a field with a validator that has to be different (not equalto) another field?

Trying not EqualTo(args) doesn't work at all

Thanks

**Comment by lepture** [comment]
@Garito define a instance method, for example, you want `foo` equals to `bar`:

```
def validate_foo(self, field):
    if field.data != self.bar.data:
        raise some error
```

**Comment by Garito** [comment]
Yeah, is what I've finally done
Thanks!
