### ISSUE TITLE
from wtforms import validators imports the incorrect one

### ISSUE THREAD

**Issue by Garito** [lepture/flask-wtf#185]
Instead to import the wtforms/validators.py it imports flask_wtf/recaptcha/validators.py

Any clue why is that?
If I try to import it from python it works as expected

I've read this: https://github.com/lepture/flask-wtf/issues/46 and seems to be related but there isn't any update to solve it

Any clue?

**Comment by lepture** [comment]
I don't understand your question.

**Comment by Garito** [comment]
I'm trying to import fields and validators from wtforms doing:
```python
from wtforms import fields, validators
```
But when I try to use:
```python
validators.Optional()
```
it raises an error saying that validators doesn't have Optional
Then I do:
```python
print(dir(validators))
```
And I found \_\_file\_\_ as a member of the module so I do:
```python
print(validators.__file__)
```
And for my surprise it points to validators.py on recaptcha instead of the asked one at wtforms

I start googleing and found the import issue back then very similar so I wonder if this is a regression or something because then someone recommends to update the library

Did I make more sense now? (Sorry for my english, it is not my main language)

**Comment by lepture** [comment]
@Garito That's weird. Can you show me the whole code and error stack?

**Comment by Garito** [comment]
The code 
```python
# -*- coding: utf-8 -*-

from sys import version_info
from collections import OrderedDict

from wtforms import Form, validators
#from flask.ext.wtf import Form

#from wtforms.fields import *
#from wtforms.validators import *

from flask.ext.babel import gettext

print(dir(validators))
print(validators.__file__)
```
The output:
```python
['RECAPTCHA_VERIFY_SERVER', 'Recaptcha', 'ValidationError', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'current_app', 'http', 'json', 'request', 'to_bytes', 'to_unicode', 'url_encode']
/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_wtf/recaptcha/validators.pyc
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
['RECAPTCHA_VERIFY_SERVER', 'Recaptcha', 'ValidationError', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'current_app', 'http', 'json', 'request', 'to_bytes', 'to_unicode', 'url_encode']
/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_wtf/recaptcha/validators.pyc
```

I understand that you are talking about this code, tell me if you need more
The point is I'm trying to create a dict2wtforms code base on this one: https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/wtf/orm.py changing the mongoengine model + field_args for a dict with all the configuration needed

What do you think? Thanks!

**Comment by lepture** [comment]
How could it be?

BTW, change the import from `flask.ext` to `flask_`:

```
from flask_wtf import Form
from flask_babel import gettext
```

**Comment by Garito** [comment]
No, it doesn't work at all
If I try to import from flask_wtf it do the same as before
But thanks for the try

**Comment by Garito** [comment]
You won't belive me: today I go back to
```python
from wtforms import validators
```
and it works as expected. Don't ask me how, I don't really know
