### ISSUE TITLE
WTF_CSRF_ENABLED needs to be set before CsrfProtect.init_app

### ISSUE THREAD

**Issue by fayazkhan** [lepture/flask-wtf#190]
Found this subtle bug where this doesn't work as expected:

    CsrfProtect().init_app(app)
    app.config['WTF_CSRF_ENABLED'] = False

It works if you reverse the order.

**Comment by hai-ld** [comment]
It seems that we encounter the same bug. I found the faulty commit and commented on it here https://github.com/lepture/flask-wtf/commit/b1d77ea962128e8d3b32b9ebea4c36a7cd1b5157. Seems to be a counter-productive optimization.

**Comment by fayazkhan** [comment]
I managed to do a workaround by doing this in my test cases:
```python
@pytest.fixture(scope='function')
def web_test_client_no_csrf(request):
    ...
    site = create_app(..., testing=True, csrf=False)
    test_client = site.test_client()
    ...
```
And modifying my `factory.py` to:
```python
def create_app(
        ..., testing=False, ..., csrf=True):
    logger = Logger('web app factory')
    ...
    app.config.update(WTF_CSRF_ENABLED=csrf)   # Set this before csrf.init_app
    ...
    csrf.init_app(app)
```

I'm not even sure if this is an ugly hack or a somewhat of an acceptable solution though.

**Comment by shreyansb** [comment]
I agree with @hai-ld, https://github.com/lepture/flask-wtf/commit/b1d77ea962128e8d3b32b9ebea4c36a7cd1b5157 causes an error that a bunch of people have had to deal with. 

In my fork of `flask-wtf`, I'm checking `app.config['WTF_CSRF_ENABLED']` from within `_csrf_protect()`. I think that should be the default behavior.

**Comment by lepture** [comment]
reverted https://github.com/lepture/flask-wtf/commit/4728faf3a8f0efadaccfcf4dfd0898b85471d419
