### ISSUE TITLE
Recaptcha form is not populated.

### ISSUE THREAD

**Issue by shivshankardayal** [lepture/flask-wtf#191]
I have config.py which has RECAPTCHA_PUBLIC_KEY in that configured properly. It used to work in past. Now I do not get recaptcha form populated with the following error in Firefox console.

Error: Missing required parameters in RecaptchaOptions: sitekey in Google's Javascript.

If I look at generated HTML then site-key is missing which should have been populated by following line widgets.py

```HTML
<div class="g-recaptcha" data-sitekey="%(public_key)s"></div>
```

**Comment by lepture** [comment]
We are using the new reCaptcha now. https://github.com/lepture/flask-wtf/pull/164
