### ISSUE TITLE
IntegerField always fails on validation

### ISSUE THREAD

**Issue by canebat** [lepture/flask-wtf#192]
Whatever I enter into the form, validating the form always fails on the IntegerField.  

    from flask.ext.wtf import Form
    from wtforms.fields import *
    from wtforms.validators import *

    class FooForm(Form):
        a = StringField('a', validators=[InputRequired()])
        b = IntegerField('b', validators=[InputRequired()])

I have data from an external source, and I try to validate that data:
    
    data = {'a': 'test', 'b': '333'}
    myform = FooForm(a = data['a'], b = data['b'])
    if myform.validate():
        print 'success'
    else:
        print myform.errors

The result is:

    {'b': [u'This field is required.']}

I've also tried with:

    b = IntegerField('b', validators=[NumberRange(min=0, max=1000)])

But this prints out:

    {'b': [u'Number must be between 0 and 1000.']}

I'm using versions:
flask: 0.10.1
flask-wtf: 0.12
wtforms: 2.0.2

**Comment by lepture** [comment]
You are doing it wrong here:

```python
myform = FooForm(a = data['a'], b = data['b'])
```

**Comment by canebat** [comment]
@lepture What's the correct way?
