### ISSUE TITLE
hidden_tag() render as None if field was removed

### ISSUE THREAD

**Issue by iurisilvio** [lepture/flask-wtf#193]
I delete a field of form initialization.

```python
class MyForm(Form):
    some_field = TextField(My Field')

    def __init__(self, *args, **kwargs):
        super(MyForm, self).__init__(*args, **kwargs)
        del self.some_field
```

I render it as a hidden field, with `{{ form.hidden_tag('csrf_token', 'some_field') }}` and it is rendered as `None`. I expected it to render an empty string or to fail.

```html
<input id="csrf_token" name="csrf_token" type="hidden" value="1438890921##2850b5f3d358c860305f2bbb4695e42003a2879f">None
```
It is rendered hidden, so it is not a critical issue, just a weird behaviour.

**Comment by davidism** [comment]
Not sure how that worked at all since `getattr` should have raised an `AttributeError`, but it's fixed now.  I clarified the undefined behavior so that only hidden fields that exist are rendered.
