### ISSUE TITLE
CSRF as a separate package

### ISSUE THREAD

**Issue by twolfson** [lepture/flask-wtf#194]
I was wondering if we would be opening to breaking out CSRF into its own package. To give you context into why someone would want this:

I am looking exclusively for a CSRF solution at the moment. Those which I found were either too single minded (wouldn't catch people missing CSRF fields in tests) or did too much/made it hard to verify they were secure.

- https://bitbucket.org/sjl/flask-csrf/overview
- https://github.com/maxcountryman/flask-seasurf

I don't plan on using WTForms at the moment (my server side validation is done by another service) and would not like the excess weight.

It looks like this could easily be done as the CSRF module doesn't use any parts from the WTForms module nor the rest of this repo (except for compatibility):

https://github.com/lepture/flask-wtf/blob/v0.12/flask_wtf/csrf.py#L18

Would we be open to breaking it out?

**Comment by lepture** [comment]
@twolfson Our form is using CSRF module: https://github.com/lepture/flask-wtf/blob/v0.12/flask_wtf/form.py#L12

My theory is form should be working together with csrf. They should be in the same repo. If you don't need forms, you can just use the csrf module, it has no harm. Otherwise, use flask-seasurf.

**Comment by twolfson** [comment]
Yep, I am aware of the rest of the repo utilizing CSRF support. However, it doesn't have to be in the same repo; it could be an external module depended on by WTForms. The benefits of this would be:

- More targeted code in each scenario
- Ability to download exactly what you need (e.g. only CSRF)

It sounds like you have made up your mind though so I will respect your decision. Thanks for the quick reply!
