### ISSUE TITLE
How to use Flask-WTF CSRF protection for Single Page Apps?

### ISSUE THREAD

**Issue by jjvattamattom** [lepture/flask-wtf#195]
I noticed that tokens generated by Flask-WTF expire in one hour and a different one is generated every request.

This will cause problems in SPAs when a page has been opened longer than an hour. XHR requests made after one hour after page-load will start failing, even if the user was active.

My workaround is to set a new token in the browser in each API call:

In the server, all API responses contain a freshly-generated token:

```python
    from flask_wtf.csrf import generate_csrf
   
    def api_response(data, error=None):
        response = {"csrftoken": generate_csrf(), "data":data}
        ...
        return make_response(jsonify(response), response_code)
```   
In the browser: we set the csrftoken on each API response.

```javascript
    then(function(result) {
        if(result.csrftoken) csrftoken=result.csrftoken;
        callback(result);
      })
```
Could you confirm if this method is still safe and fast? I am not too sure about using generate_csrf directly. With the increasing popularity of SPAs, documenting this in Flask-WTF seems important.

**Comment by lepture** [comment]
1. server: You can add the token in your response header with `@after_request` hook. 
2. client: Send token with CSRF token headers
