### ISSUE TITLE
404 Bad Request but there is {{ form.csrf_token }} and SECRET_KEY in form and config

### ISSUE THREAD

**Issue by Avrong** [lepture/flask-wtf#197]
![snip_20150914180323](https://cloud.githubusercontent.com/assets/6342851/9853196/1a1e238e-5b0b-11e5-8be8-92ec5aa92a9c.png)

Yesterday application with this form worked normal, but today - error...
...and flask also swears about g.flask.is_authenticated(). Changed to g.flask.is_authenticated...
...and flashes does not work...

forms.py
```python
class LoginForm(Form):
    email = StringField('email', validators=[DataRequired('...'), Email('...'), Length(3, 50, '...')])
    password = PasswordField('password', validators=[DataRequired('...'), Length(3, 50, '...')])
    submit = SubmitField('submit')
```

template
```html
<div class="container">
    {% with flashes = get_flashed_messages() %}
    {% if flashes %}
    {% for flash in flashes %}
    <div class="alert alert-{{ category }} alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>{{ flash }}</div>
    {% endfor %}{% endif %}{% endwith %}
    <form class="form-signin" method="POST" role="form" action="{{ url_for('admin_login') }}">
        {{ form.csrf_token }}
        {{ form.email(class="form-control", id="inputEmail", placeholder="...", type="email", maxlength="30") }}
        {{ form.password(class="form-control", placeholder="...", id="inputPassword", maxlength="50") }}
        {{ form.submit(class="btn btn-lg btn-primary btn-block", value="...") }}
    </form>
</div>
```

**Comment by shipperizer** [comment]
same issues here

**Comment by lepture** [comment]
What happened on your "today"?

**Comment by shipperizer** [comment]
It was saying Bad Request.
I was switching to the newest flask-login (0.3.0) where they switched the is_authenticated method to a property...
I reset the libraries but still not working, then I added some logging on the library code, and it worked till this morning, then after another reinstall everything is broken again....
really no ideas, im clueless

**Comment by shipperizer** [comment]
@Avrong I guess you are using flask_login? If yes could you check your LoginManager session_protection property?
In my case was set to 'strong' and given that https://github.com/maxcountryman/flask-login/commit/a96de342eae560deec008a02179f593c3799b3ba was introduced and it's clearing the session at every request(the hook seems to be global for each request, so it's not bound to a special login view...that's why it's breaking my other forms)
just taking it out made everything work fine....nothing to blame on flask-wtf

**Comment by Avrong** [comment]
Problem not solved but app works if
```html
{{ form.csrf_token }}
```
change to
```html
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
```

**Comment by lepture** [comment]
@Avrong that's weird. 

```
{{ form.csrf_token }}
```

should be the same as

```
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
```

**Comment by davidism** [comment]
Can't reproduce this.  The two statements are indeed equivalent.
