### ISSUE TITLE
How can I do multiple file uploads with one input ?

### ISSUE THREAD

**Issue by rlam3** [lepture/flask-wtf#204]
How can I do multiple file uploads with one input ? What do I have to add to FileField()??

**Comment by rlam3** [comment]
Javascript workaround? 

$('#element')[0].setAttribute("multiple","true");

**Comment by lepture** [comment]
is `FileField(multiple=true)` working?

**Comment by rlam3** [comment]
no this doesn't

I'm getting the following error, is there a way for you to just add a boolean or subclass this fileinput with multiple file input?
```
    return self.field_class(*self.args, **kw)
TypeError: __init__() got an unexpected keyword argument 'multiple'
```

**Comment by Junnplus** [comment]
@rlam3 @lepture 
`{{ form.files(multiple="multiple") }}` and `form.files.raw_data`

**Comment by davidism** [comment]
This is an issue with WTForms, which doesn't provide a field that supports multiple uploads.  I submitted a patch to add a `MultipleFileField` to WTForms: wtforms/wtforms#281.
