### ISSUE TITLE
Is there a way to capture data from a select field without a submit button?

### ISSUE THREAD

**Issue by callmeskywalker** [lepture/flask-wtf#207]
What I am looking for is after a user makes a selection, that is when there is a change in the selected item, to capture that the data from the submit field, and then dynamically update a value on the web-page. Ideally the solution will involve flask and python.

**Comment by justanr** [comment]
You'd probably want to use JavaScript on the frontend to handle that. I've been playing with Angular lately and it has some really nice form handling capabilities.

**Comment by callmeskywalker** [comment]
I was hoping for an option in the form that would handle it. I will check out Angular though, thanks for the suggestion.

**Comment by justanr** [comment]
You could do it completely server side, but it'd cause a full page reload and you'd still need some sort of submission mechanism. To capture an on change event requires JavaScript anyways.

I'd recommend looking at Angular, React, and JQuery to see what fits your brain the best. There's also Ember and some others, but I'm not as familiar.

**Comment by callmeskywalker** [comment]
Thanks for the pointers. I will take a look at some of those. I'll take your word re. Angular.
