### ISSUE TITLE
form.hidden_tag() generates unnecessary div

### ISSUE THREAD

**Issue by txtsd** [lepture/flask-wtf#217]
If the input types are already hidden, what is the purpose of the div?
```
<input id="csrf_token" name="csrf_token" type="hidden" value="1452782070##2b535ebc0d609f21b85bb776d59247560414b7ff">
<input id="next" name="next" type="hidden" value="">
```
is a cleaner output than
```
<div style="display:none;"><input id="csrf_token" name="csrf_token" type="hidden" value="1452782070##2b535ebc0d609f21b85bb776d59247560414b7ff"><input id="next" name="next" type="hidden" value=""></div>
```
and avoids inlined css.

**Comment by pjvandehaar** [comment]
Search for `DIV tag` on https://flask-wtf.readthedocs.org/en/latest/quickstart.html?highlight=div%20tag

**Comment by davidism** [comment]
@lepture Omitting the div appears to be valid HTML 5, but not 4.  No decent HTML parser would be confused by the briefer syntax.  Maybe it's time to re-evaluate removing this?

**Comment by lepture** [comment]
@davidism aye

**Comment by davidism** [comment]
Noticed that the docs contradicted themselves by rendering another field without a wrapping block right after the hidden block.  So we weren't even following our own rules. ;-)
