### ISSUE TITLE
Looking for a way to do multi-step/page sign up.... 

### ISSUE THREAD

**Issue by rlam3** [lepture/flask-wtf#221]
I'm looking for a way to do multiple page / step sign up.... I'm not sure how to do this with wtf forms. Or is there a better way of doing this type of signup process where I can get data from two different forms from two different pages? 

ex:

signup/part1
- get some more data
- render next form

signup/part2
- get some form data
- redirect to /submit with data from part 1 and part 2

signup/submit
- user verifies values and hits submit.
- takes data from part 1 and part 2 and executes necessary code
- redirects to another page

**Comment by davidism** [comment]
Store the data in hidden fields, or the session.
