### ISSUE TITLE
Nginx and Gunicorn with CsrfProtect Referrer checking failed - origin does not match due to port comparison in csrf.same_origin function

### ISSUE THREAD

**Issue by mkmoisen** [lepture/flask-wtf#223]
[flask_wtf.csrf.same_origin()](https://github.com/lepture/flask-wtf/blob/master/flask_wtf/csrf.py#L262) returns False when Nginx, on one port, is referring the request to Gunicorn, on a different port, because of the port comparison.

This fails when I submit a form.

Here is the function:

    def same_origin(current_uri, compare_uri):
        parsed_uri = urlparse(current_uri)
        parsed_compare = urlparse(compare_uri)

        if parsed_uri.scheme != parsed_compare.scheme:
            return False

        if parsed_uri.hostname != parsed_compare.hostname:
            return False

        if parsed_uri.port != parsed_compare.port:
            return False
        return True

I can verify this by modifying the function to print out `parsed_uri.port` and `parsed_compare.port`.

In my case, `parsed_uri.port` is None, while `parsed_compare.port` is the port that Gunicorn is running on. 

`parsed_uri.netloc` is `<myHost>`, while `parsed_compare.netloc` is `<myHost>:<myGunicornPort>`

My nginx is running on 443/SSL.

I created a [pull request](https://github.com/lepture/flask-wtf/pull/225) and removed the port comparison, and my requests now go through. The one downside is that if you had a rouge application on your host on a different port, it could bypass this.

Incidentally, Djano's CSRF doesn't appear to be checking ports, only hosts. What is the purpose of flask_wtf doing a port comparison? Here is the relevant [Django](https://docs.djangoproject.com/en/1.9/_modules/django/middleware/csrf/) code, search for "if not any(is_same_domain(referer.netloc, host) for host in good_hosts):"

Also, I like how Django uses more than just the current host to be considered valid. With flask_wtf, if my Nginx is on another host, the `same_origin` will always return False.

My pull request failed because after removing the two lines, coverage dropped below 90%.

**Comment by davidism** [comment]
I can't reproduce this issue. This is most likely an issue with your configuration, not with Flask-WTF's same origin check.

~~~
server {
        listen 8443 ssl;
        server_name davidism.localdomain;
        ssl_certificate /srv/http/server.pem;
        ssl_certificate_key /srv/http/server.pem;

        location / {
            proxy_pass http://localhost:8000;
            proxy_set_header Host $host$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
        }
    }
~~~

~~~python
rom flask import Flask
from flask import render_template_string
from flask_wtf import CsrfProtect

app = Flask(__name__)
app.secret_key = b'dev'
csrf = CsrfProtect(app)

@app.route('/', methods=['GET', 'POST'])
def index():
    return render_template_string('{{csrf_token()}}<form method=post>'
           '<input name=csrf_token value={{ csrf_token() }}>'
           '<input type=submit>'
           '</form>')
~~~

    gunicorn example:app

I tried pretty hard to make it fail, and the only time it did was when I used a non-standard port (8443) and didn't add the port to the Host header.

**Comment by davidism** [comment]
related: pallets/flask#1023
