### ISSUE TITLE
how do i keep the original filestorage object inside the form when validation errors?

### ISSUE THREAD

**Issue by rlam3** [lepture/flask-wtf#226]
how do i keep the original filestorage object inside the form when validation errors?

scenario:

input 1 ok
input 2 failed
fileinput 1 ok

user POSTs

then error/validation on input 2 is not good, so it redirects them back to the same page with error in message box. 

However, the fileinput is gone but is valid. It dissapeared/got cleared out. How do I not let this happen?

Thanks!

**Comment by Junnplus** [comment]
why not use `render_template`?

**Comment by rlam3** [comment]
@Junnplus the point is that after posting.. the fileinput field doesn't retain any data from the valid upload because the errors from input 2 failed. this causes form.validate_on_submit() fails, the filestorage data from file input is gone.

**Comment by davidism** [comment]
This is browser behavior, not something we can change.  We don't know the path of the file, nor can you set the path for a file input, it's a security issue.  If you want to store the files, you'll need to do so manually and add logic to handle that on the frontend and backend.
