### ISSUE TITLE
SecureForm and CsrfProtect

### ISSUE THREAD

**Issue by roganov** [lepture/flask-wtf#228]
I'm not sure whether the two methods of csrf protection must be used together,
tt seems that if CsrfProtect is configured then there is no need for SecureForm.
Am I correct or I'm missing something?
I'm asking this because SecureForm depends on flask's `current_app`, which means  unit testing forms that inherit from SecureForm requires flask's application context.

**Comment by davidism** [comment]
http://flask-wtf.readthedocs.io/en/latest/csrf.html#why-csrf

> Flask-WTF form is already protecting you from CSRF, you don’t have to worry about that. However, you have views that contain no forms, and they still need protection.

`CsrfProtect` works for *all* requests, not just ones with `flask_wtf.Form`.  Useful for api requests.

Yes, you need the app context, this is a standard requirement when testing most Flask related things.
