### ISSUE TITLE
WTForms 3.0 will break flask-wtf's csrf

### ISSUE THREAD

**Issue by zoltan-fedor** [lepture/flask-wtf#229]
I was working with the dev version of WTForms 3.0 (https://github.com/wtforms/wtforms) and it seems they have made some changes like removing the wtf.ext extensions, some of which do break flask-wtf, like the lack of the csrf extension.

**Comment by roganov** [comment]
duplicate of https://github.com/lepture/flask-wtf/issues/216

**Comment by zoltan-fedor** [comment]
Sorry, you are right
