### ISSUE TITLE
Validators | form.validate_on_submit() | implicit validation

### ISSUE THREAD

**Issue by disarticulate** [lepture/flask-wtf#231]
I believe I just spent several hours trying to debug this issue without any errors thrown.

It makes sense, but:
form.validate_on_submit() returns False if _any_ of the  wtforms input fields are absent from the page, even if none of them absent fields have validators.

I'm unsure how one might notify without breaking or perhaps document a flag:
`form.validate_on_submit(requireAllFormFields_returned=True)`

**Comment by justanr** [comment]
You need to declare the field with an Optional() validator, which comes from the wtforms library

**Comment by disarticulate** [comment]
sounds good, just thought it'd be nice to vent.
