### ISSUE TITLE
There quite a few updates.. maybe a release?

### ISSUE THREAD

**Issue by lipis** [lepture/flask-wtf#234]

**Comment by lipis** [comment]
So that means that we'll have new release or?

**Comment by waynew** [comment]
I'm not affiliated with this project in really any way... but if you're wanting features that are still under development, you can always [install from a git branch](http://stackoverflow.com/a/20101940/344286)

**Comment by lipis** [comment]
I'm aware of that.. but I prefer something more stable.. like a release tag :)

**Comment by waynew** [comment]
So use the git hash - that's just as stable as a release tag :P

**Comment by lipis** [comment]
and it's very convenient as well.. how I didn't think of that!! thanks again @waynew.. you saved my life.. no need to create any releases any more.. everyone should actually stop releasing shit and we should just switch to git hashes.. they are small human readable and very useful..

**Comment by lepture** [comment]
Will bump a version later these days.

**Comment by lipis** [comment]
@lepture Busy with life?!
