### ISSUE TITLE
Docs say "will be deprecated in 0.9.3" but that is an old release

### ISSUE THREAD

**Issue by jeffwidman** [lepture/flask-wtf#236]
https://flask-wtf.readthedocs.org/en/latest/form.html#html5-widgets

> We will drop html5 module in next release 0.9.3.

This seems a bit weird to have in the latest docs, since that is quite an old release. 

Should the docs be updated, or the code removed now that it's been deprecated for quite some time?

**Comment by homeworkprod** [comment]
The docs state that the code would have been *dropped*, not deprecated.

Since it's been 2.5+ years as well as eight releases later, both the note in the docs as well as the referenced code itself should be removed, I'd say.
