### ISSUE TITLE
request.json vs request.get_json() and request.is_json

### ISSUE THREAD

**Issue by asplake** [lepture/flask-wtf#245]
Since upgrading to Flask 0.11 and moving from flask.ext.wtf to flash_wtf I'm getting lib/python3.4/site-packages/werkzeug/local.py:343: DeprecationWarning: json is deprecated.  Use get_json() instead.

Guessing that occurrences of request.json now be replaced with request.get_json() or perhaps request.is_json when used in a conditional.

It looks to be a small change and I'd be prepared to prepare a pull request if you wish but I'm unsure of what other impact it might have.

Cheers,
Mike

**Comment by davidism** [comment]
A pull request addressing this would be appreciated.  `is_json()` only checks the content type, so make sure it would actually make sense to use it in place of `get_json()`.

**Comment by achals** [comment]
#246 should address this.
