### ISSUE TITLE
Rename Form to FlaskForm

### ISSUE THREAD

**Issue by davidism** [lepture/flask-wtf#249]
A common issue users have is that they imported `wtforms.Form` when they meant `flask_wtf.Form`, or vice versa, or they imported both and one is masking the other.  We should rename `flask_wtf.Form` to `flask_wtf.FlaskForm`, and treat `Form` as a deprecated alias that raises a warning when it is used.

This also makes it easier to subclass both types of form in one file.  For example when you want to create forms for `FormField` and only have CSRF handling in the main form.  Right now you need to import one of the forms with an alias.

**Comment by lepture** [comment]
I agree.

**Comment by surlyjake** [comment]
Could you release and update the version in pypi so that users using pip can follow the new documentation?

**Comment by davidism** [comment]
You're looking at the dev docs.  Use the menu in the bottom right corner to select the stable docs.  I do plan on making a release "soon", but want to get a few more changes in.

**Comment by unnamedd** [comment]
Hi @davidism,

how much time is needed to update to 0.14 on PIP ? I saw that you have a commit changing to last version, but it isn't reflected yet.

**Comment by davidism** [comment]
That's the development version, there's no changes yet.
