### ISSUE TITLE
Naming a field validate breaks validation

### ISSUE THREAD

**Issue by RyanEager** [lepture/flask-wtf#254]
If you created a simple form:

```
class MyForm(Form):
    name = StringField('Name', validators=[ DataRequired() ])
    validate = SubmitField('Validatel)
    submit - SubmitField('Submit')
````

`form.validate_on_submit()` always passes even if there is no data, all validators are ignored. If you change the name to `validateForm` the issue is gone.

Tested on:
```
Flask-WTF==0.12
WTForms==2.1
```

**Comment by davidism** [comment]
If anything, this is an issue with wtforms. However, this isn't very surprising, it will happen with any Python object if you overwrite an attribute that it needs.
