### ISSUE TITLE
FileField seems to break if request.form is passed to form constructor

### ISSUE THREAD

**Issue by Cheaterman** [lepture/flask-wtf#255]
Hello buddies, I hope you're doing good!

Today I was testing FileField and trying to make a cool file upload form, when I stumbled upon an issue which is described more in-depth here:

https://github.com/pallets/flask/issues/460

I think we should find a solution to this somehow, because it's not very cool or consistent to have all forms use request.form as argument except the ones with files?

Thanks in advance buddies ^__^

**Comment by Cheaterman** [comment]
Also I had a very hard time finding the above issue to fix my problem, which is why I opened this bug in the first place. More documentation, less pain!

**Comment by davidism** [comment]
#212

**Comment by Cheaterman** [comment]
Sorry david, indeed it was a duplicate, thanks for fixing it, you're awesome ^__^
