### ISSUE TITLE
Form -> FlaskForm rename breaks custom metaclasses

### ISSUE THREAD

**Issue by ThiefMaster** [lepture/flask-wtf#262]
When using a custom metaclass you usually subclass `FormMeta`. This fails thanks to the different metaclass used to show the deprecation warning (#249):

> TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

It's an easy fix (not using the deprecated `Form` class) but still, I think this should at least e mentioned in the docs.

cc @davidism

**Comment by davidism** [comment]
Hmm, I was too clever!  Should I just move the warning to `__init__` and have it trigger on instantiation rather than definition?  I didn't do that initially because I thought it would be less clear.
