### ISSUE TITLE
hidden_tag changes in v0.13 are not backward-compatible.

### ISSUE THREAD

**Issue by jcass77** [lepture/flask-wtf#263]
Upgrading from release 0.12 to 0.13 breaks a specific test case that I have in one of my applications.

The exception raised is ``AttributeError: 'UnboundField' object has no attribute 'data'``.

I've defined a hidden field in my form:

```python
class ChangePasswordFormHref(ChangePasswordForm):
    href = HiddenField('Href')
```

For some reason the ``href`` field is not populated when simulating a post with:

```python
resp = self.client.post('/forgot/change', data={'password': 'P@55word_mock1234', 'password_again': 'P@55word_mock1234', 'href': account.href, }, follow_redirects=True)
```

What makes this even more perplexing is that the test case only breaks if it is run as part of a batch of similar tests. Running it in isolation works fine.

The ``hidden_tag`` field is included in my the html template:

```html
{% from '_formhelpers.html' import render_field %}
<form id="forgot_change_form" method="post">
  {{ form.hidden_tag() }}
  {{ render_field(form.password, placeholder='Password', type='password') }}
  {{ render_field(form.password_again, class='form-control', placeholder='Password (again)', type='password') }}
  <fieldset class="ui-grid-solo">
    <div class="ui-block align-right">
      <a href="#" onclick="$('#forgot_change_form').submit()" data-role="button" data-mini="true" data-inline="true">Submit</a>
    </div>
  </fieldset>
</form>
```

The exception occurs when I try to access the hidden ``href`` field in the view:

```python
def forgot_change():
    form = ChangePasswordFormHref()

    if request.method == 'GET':
        try:
            account = current_app.stormpath_manager.application.verify_password_reset_token(request.args.get('sptoken'))
            form.href.data = account.href
        except StormpathError:
            abort(400)

    if form.validate_on_submit():
        try:
            account = current_app.stormpath_manager.client.accounts.get(form.href.data) # <-- Exception
            account.password = form.password.data
            account.save()
```
I've tried to pinpoint the issue without any luck - it might be that I am using Flask-WTF in a non-standard way?

**Comment by davidism** [comment]
Please include the full traceback.

**Comment by davidism** [comment]
This doesn't appear to have anything to do with `hidden_tag`, since you're not using the template when causing the error, you're bypassing it and using the test client.

**Comment by davidism** [comment]
I can't reproduce your error.  Please update with a [Minimal, Complete, and Verifiable Example](http://stackoverflow.com/help/mcve).

Either you're not using a Flask-WTF form or you've disabled CSRF elsewhere, otherwise this would fail because you aren't sending a CSRF token.  Assuming that's the case, I don't get the error you've posted.
