### ISSUE TITLE
Question. Using of `FlaskForm`, Is there no need to make any *single* configuration?

### ISSUE THREAD

**Issue by DanielTimLee** [lepture/flask-wtf#265]
From the documents below, 
`https://flask-wtf.readthedocs.io/en/stable/form.html`
> Without any configuration, the FlaskForm will be a session secure form with csrf protection. We encourage you do nothing.

It says, there is no need have any configuration, 
does it means, If we use only `FlaskForm`, 
than we don't have to pass `{{ form.csrf_token }}` to Jinja Filter?

**Comment by davidism** [comment]
No, it means you don't have to configure anything.  You still have to write code to use it.

**Comment by DanielTimLee** [comment]
Thanks!

**Comment by DanielTimLee** [comment]
So It means,

I don't need to add
`CSRFProtection(add)`
Right?
