### ISSUE TITLE
CSRF session expire 

### ISSUE THREAD

**Issue by erwinyusrizal** [lepture/flask-wtf#267]
Hi, I have an issue when CSRF session expired, and I do submit form, it returns

`TypeError: csrf_error() takes no arguments (1 given)`

any idea?

Thanks

**Comment by davidism** [comment]
Assuming you're still using the deprecated `@error_handler`, the decorated function takes one parameter, `reason`.

**Comment by erwinyusrizal** [comment]
@davidism 

yes I still use flask-wtf version 0.13.1 and use this error handler

`@csrf.error_handler
def csrf_error():
    return render_template('errors/400.html'), 400`

I checked some of other issue, you said it's deprecated but how do I import the CsrfError ?

`@app.errorhandler(CsrfError)`

Thanks

**Comment by erwinyusrizal** [comment]
Ok I got what you meant. It's working now, sorry for my mistake :)

Thanks
