### ISSUE TITLE
Use Case: flask-wtf csrf protection in Angular 2 Application

### ISSUE THREAD

**Issue by TheJimFactor** [lepture/flask-wtf#282]
Is there a way to enable csrf protection in an angular 2 application? I don't use flask to render any templates, so I can't get the csrf token via  `{{ csrf_token() }}` or `{{ form.csrf_token }}`.

The stack is: nginx to serve up the Angular 2 application, then a reverse proxy for the flask application, that is validating form data being sent to it. The flask application only sends/receives form data/json and never renders a template.

It was recommended to simply expose the CSRF via a get method - http://flask.pocoo.org/snippets/3/ 

> Just define a GET method which returns the CSRF token.

Is there a way to grab a csrf token from flask-wtf's csrf extension??

**Comment by davidism** [comment]
#280 and various others

**Comment by lepture** [comment]
We can add the code snippet in https://flask-wtf.readthedocs.io/en/stable/csrf.html
