### ISSUE TITLE
X-CSRFToken checking is case sensitive

### ISSUE THREAD

**Issue by veggiedefender** [lepture/flask-wtf#284]
The [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html) (section 4.2) states that header field names are case insensitive. But since flask-wtf gets the header from a [dictionary](https://github.com/lepture/flask-wtf/blob/master/flask_wtf/csrf.py#L185-L187), it only accepts csrf tokens with the correct capitalization.

This looks like a really minor detail but [fetch](https://fetch.spec.whatwg.org/#terminology-headers) which appears to be the successor of xmlhttprequests automatically lowercases headers without an option to preserve case, making fetch pretty much incompatible with flask-wtf in terms of sending over csrf tokens.

**Comment by davidism** [comment]
If you're noticing header case issues, that sounds like an issue with Werkzeug, not Flask-WTF.

**Comment by veggiedefender** [comment]
You know what, you're right! I did some poking around in the source code and pinned the error down to getting stuff from the session. After further research I found that fetch doesn't send cookies like XMLHttpRequest!

I added `credentials: 'same-origin'` which adds the cookies to the fetch request and it works great now, and it does indeed ignore case like it's supposed to.

Sorry for bothering you!

(If you ever add documentation for sending csrf tokens with fetch, it would probably be good to add that since it is a sneaky problem)

**Comment by vsoch** [comment]
Holy cow I hit this same issue! I was trying different methods of specifying the header, along with using flask request.args vs. request.data, etc. What got it working for me was exactly what you mentioned @veggiedefender, adding the `credentials: "same-origin"` So others don't need to struggle through this, here is an example of what worked for me finally:

```
        // On click of a path, fetch updated table
        $(".folder").click(function(){
            var csrf_token = "{{ csrf_token() }}";
            var path = "{{ path }}" + $(this).attr('data-name');

            fetch('/globus/{{ endpoint.id }}?path=' + path, {
                headers: { "X-CSRFToken": csrf_token },
                credentials: 'same-origin',
 	        method: 'POST' })
            .then((response) => response.json())
            .then(function(data) {
                console.log(data);
             }).catch(function(err) {
                console.log(err);
             });
        });
```
Then in the view I get the path from args after all

```
    # Post indicates browsing the tree, with an additional path to parse
    if request.method == "POST":
        path = request.args.get('path') or None
```
the or None is added in case the post is an empty string `` I want it to remain None in favor of that :)

And excellent profile picture and name @veggiedefender ! Do you defend all vegetables or just cute cartoon ones? :smile:
