### ISSUE TITLE
WTF_CSRF_SSL_STRICT with subdomains

### ISSUE THREAD

**Issue by roganov** [lepture/flask-wtf#285]
Currently referrer checking fails if hosts don't match exactly, which is not desirable for applications that use subdomains.
To address this, we can either introduce a new configuration option that specifically allows subdomains, or alternatively referrers can be "normalized" to `flask.SERVER_NAME` and then checked, though I'm not sure if this is secure.

**Comment by davidism** [comment]
I don't use multiple domains; if you need this fixed, you or someone else is going to have to make a patch.

**Comment by rlam3** [comment]
@roganov I think I'm having a similar situation. Have you found a workaround?

**Comment by davidism** [comment]
@rlam3 if you're having a similar situation, please add an example demonstrating it.

**Comment by roganov** [comment]
@rlam3 I just disabled WTF_CSRF_SSL_STRICT.
This is probably insecure, but unfortunately I don't have time right now to provide a merge request. Hopefully I'll have an opportunity some time later.

**Comment by erwinyusrizal** [comment]
I'm facing the same issue with csrf using multiple/sub domains, below is my details:

```
SERVER_NAME: 'domain:3000'

// blueprint api subdomain set to: 'api' ==> api.domain:3000
// blueprint dashboard set to: 'dashboard' ==> dashboard.domain:3000
```

Any idea to fix this?

Thanks

**Comment by erwinyusrizal** [comment]
this is strange, just restart the server and now the csrf is working now

**Comment by erwinyusrizal** [comment]
I got it, it's because similar to @roganov solutions, I disabled WTF_CSRF_SSL_STRICT
