### ISSUE TITLE
import RecaptchaField

### ISSUE THREAD

**Issue by slippers** [lepture/flask-wtf#286]
the help for RecaptchaField is importing from the wrong place:)  moved to flask_wtf.recaptcha.  

i can't seem to find where to change this in the docs.

[Recaptcha](https://flask-wtf.readthedocs.io/en/stable/form.html#)

```
from flask_wtf import FlaskForm, RecaptchaField
```
should be
```
from flask_wtf.recaptcha import RecaptchaField
```

**Comment by davidism** [comment]
That import works fine.
