### ISSUE TITLE
Boolean Field not rendered with quick_form

### ISSUE THREAD

**Issue by lormayna** [lepture/flask-wtf#292]
Hello, I'm try to render a simple form with flask-wtf and quick_forms.
This is my  form:
`class SignupForm(FlaskForm):

    username = StringField('Username', [validators.Length(min=4, max=25)])

    accept_tos = BooleanField('I accept the TOS', [validators.DataRequired()])

    prefs = BooleanField()`

This is the template:
{{ wtf.quick_form(form, action="/signup") }}

Unfortunately the BooleanFields are not rendered. All the other fields look correct.

**Comment by davidism** [comment]
`quick_form` is not part of Flask-WTF.
