### ISSUE TITLE
Is it OK to serve CSRF token from JSON REST endpoint?

### ISSUE THREAD

**Issue by davidthornton** [lepture/flask-wtf#293]
I understand this page to mean that http://flask-wtf.readthedocs.io/en/stable/csrf.html the app server which serves the HTML must be the same app server against which the "AJAX" calls are being made.

However, I'm serving my pages from S3 to make them load a bit faster than if they were served from the app server. In that case, I can't include a CSRF token on those static assets! What I've done is "mocked out" essentially the GET call to the form by exposing a JSON REST endpoint like so:

```
from flask import Blueprint, jsonify
from flask_wtf.csrf import generate_csrf

csrf = Blueprint('csrf', __name__)


@csrf.route('/csrf', methods=['GET'])
def get_csrf_token():
    return jsonify({
        'csrf_token': generate_csrf(),
    })
```

My question is, does this endpoint work exactly as though the form were requested with an `Accept: text/html` header?

Does it expose my app to any vulnerabilities I am not aware of? If not, would this package benefit from a pull request that implements this functionality in a reusable way?

**Comment by davidism** [comment]
You're fine.
