### ISSUE TITLE
Caching per-request token on flask.g is problematic

### ISSUE THREAD

**Issue by rsyring** [lepture/flask-wtf#301]
In https://github.com/lepture/flask-wtf/commit/653f662306b65b81e301cae45e42474cd1652609 a change was made to start caching the csrf_token on `flask.g` instead of `flask.request`.  However, `flask.g` is application level in scope since v0.10:

> Starting with Flask 0.10 this is stored on the application context and no longer on the request context 

http://flask.pocoo.org/docs/0.12/api/#flask.g

This makes it impossible for subsequent requests to work with the CSRF token because once the token has been generated for an application instance, and saved in that request's session, no other subsequent requests will cause a session to be generated, thereby preventing CSRF from working for things like form fields.

**Comment by rsyring** [comment]
See [this commit](https://github.com/lepture/flask-wtf/pull/302/commits/60d324acfb8dfca94476523d2c1f9199b788388f) for a test case that exposes the bug.

**Comment by mitsuhiko** [comment]
An application context is generated per request. So this should not change anything.

**Comment by rsyring** [comment]
Ok, so I may be wrong on understanding the scope of `flask.g`, but the tests on my PR:

https://github.com/lepture/flask-wtf/pull/302/files#diff-93d2b8546b1110e297d3eee61336f255

Show there is some kind of bug involved.  If you keep the test but remove the code changes, the test fails (and I don't believe it should).

**Comment by mitsuhiko** [comment]
That's because you are manually re-using an app context.

**Comment by rsyring** [comment]
Wow, I've completely misunderstood the nature of the app context for years.  I thought that it should be present as long as the app instance was present.  Having now read the docs on Flask's app context, I understand my problem.  I'll have to rethink how [I'm doing testing in Keg](https://github.com/level12/keg/blob/63165673e188f9df38d548e95feb6300351a8a9a/keg/testing.py#L35), since that is really where my problem is.
