### ISSUE TITLE
How to use the built-in translations provided by WTForms

### ISSUE THREAD

**Issue by greyli** [lepture/flask-wtf#303]
As describe in WTForms's documentation [here](http://wtforms.readthedocs.io/en/latest/i18n.html#using-the-built-in-translations-provider), we can define a base class to set the default locale app-widely:
```python
from wtforms import Form

class MyBaseForm(Form):
    class Meta:
        locales = ['es_ES', 'es']
```
How to achieve this with Flask-WTF?

**Comment by greyli** [comment]
Actually, I don't know too much about i18n. 

Install `Flask-Babel` and set `BABEL_DEFAULT_LOCALE` will do the same thing. However, I want to know is it possible to make it work without `Flask-Babel (Babel)`?

**Comment by lepture** [comment]
@greyli No. You must use Flask-Babel to enable i18n.

**Comment by greyli** [comment]
Thanks!

**Comment by greyli** [comment]
@lepture Sorry to disturb you, I thought maybe there is a misunderstanding. Actually, I just want to set the default error message's language to Chinese (localization). How to do it without Flask-Babel or Babel just like use pure WTForms? 

Similar to this [SO question](https://stackoverflow.com/questions/33023094/wtforms-l10n-and-i18n-not-working).

**Comment by greyli** [comment]
The working code with pure WTForms:
```python
class MyBaseForm(Form):
    class Meta:
        locales = ['zh']

class HelloForm(MyBaseForm):
    name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField()
```
Then the error message will be displayed in Chinese.

**Comment by lepture** [comment]
@greyli The current implementation is using Babel to determine the language automatically. In this case, you will have to use Babel.

**Comment by greyli** [comment]
Is it possible to add support for this usage? 

I thought it's a common need. Sometimes people don't want to add i18n/l10n support, the only thing they want is using the specific built-in translations.

**Comment by greyli** [comment]
If you think it's ok, I'll submit a PR.

**Comment by lepture** [comment]
Sure, if it won’t take too much work.
