### ISSUE TITLE
Depreciation warning is less helpful then it could be

### ISSUE THREAD

**Issue by fake-name** [lepture/flask-wtf#304]
This is a kinda dumb issue, but I'm going through a bunch of depreciation warnings, and it's bothering me.

Basically, If I have out-of-date dependencies, I get error messages from flask like:

`FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.` or `"flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.`

The problem here is that *sometimes*, the first aspect of the import is the part that's out of date, sometimes it's the second part of the import, and sometimes it's the entire thing (across multiple flask ext libraries):

 - `from FlaskForm import Form`  (This is common for lots of stuff that was in the `flask.ext.***` namespace
 - `from flask_wtf import FlaskForm`  (Correct option, in this case)
 - `import FlaskForm`     

Is there any reason the error message can't be: `FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "flask_wtf.FlaskForm" and will be removed in 1.0.`

I'm not sure how the depreciation warning is getting thrown, but it takes what would normally be a simple replacement and turns it into a "dig through the docs to figure out what part actually changed".

**Comment by fake-name** [comment]
Basically, yes. That would solve the issue.

**Comment by lepture** [comment]
@fake-name You can make a PR for it.

**Comment by sci-web** [comment]
from flask_wtf import FlaskForm
doesn't work for me either:
rom flask_wtf import FlaskForm
ImportError: cannot import name FlaskForm

**Comment by sci-web** [comment]
> from flask_wtf import FlaskForm (Correct option, in this case)
doesn't work for me either:

from flask_wtf import FlaskForm
ImportError: cannot import name FlaskForm
flask --version
Flask 0.12.2
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609]

And all these depreciation warnings are really bothering :(

**Comment by sci-web** [comment]
> from flask_wtf import FlaskForm (Correct option, in this case)

— doesn't work for me either:
from flask_wtf import FlaskForm
ImportError: cannot import name FlaskForm

flask --version
Flask 0.12.2
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609]

And all these depreciation warnings are really bothering :(

**Comment by Ansilacerda** [comment]
You need to put this:
from flask_wtf import FlaskForm

In the code in your project Form:

Example: 
class LoginForm(Form):
to
class LoginForm(FlaskForm):
