### ISSUE TITLE
problem with 0.14.2 on python-2.7.13

### ISSUE THREAD

**Issue by buzzdeee** [lepture/flask-wtf#310]
while looking at updating the OpenBSD package from 0.9.4 to 0.14.2, I run into trouble building the package for python 2.7:

In the ports Makefile there is a post-build step:
```
post-build:
        @cd ${WRKSRC}/docs && \
                ${SETENV} ${MAKE_ENV} ${MAKE_PROGRAM} SPHINXBUILD=sphinx-build${MODPY_BIN_SUFFIX} html
```
which basically resembles to cd docs && sphinx-build html

using sphinx-build-3 (based on python3) it all just works, but using the sphinx-build based on python 2.7 sphinx-build fails with:

raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'Flask-WTF' distribution was not found and is
required by the application

Sphinx is version: py-sphinx-1.4.8

comparing the conf.py from 0.9.4 and the 0.14.2 it seems the newer version has:
dist = get_distribution('Flask-WTF')

whereas the older version had version and revision hardcoded.

This get_distribution() call works with python3, but not python2, my current workaround is to hardcode the version and revision as done in 0.9.4

**Comment by davidism** [comment]
You need to install Flask-WTF in the virtualenv to build the docs.  Create a virtualenv if you haven't, and `pip install -e .` from the project directory, then continue building the docs.
