### ISSUE TITLE
readthedocs is out of date regarding csrf_enabled

### ISSUE THREAD

**Issue by jeffcjohnson** [lepture/flask-wtf#313]
The [rst](https://github.com/lepture/flask-wtf/blob/master/docs/form.rst) file has been updated:

```
form = FlaskForm(meta={'csrf': False})
```

but [readthedocs](https://flask-wtf.readthedocs.io/en/stable/form.html#module-flask_wtf) still has the deprecated form:

```
form = FlaskForm(csrf_enabled=False)
```

**Comment by davidism** [comment]
You're looking at the current docs. The next release will reflect any changes since then.
