### ISSUE TITLE
"ValueError: too many values to unpack" with SQLAlchemy 1.2.2

### ISSUE THREAD

**Issue by commandtab** [lepture/flask-wtf#324]
When using SQLAlchemy 1.2.2 with Flask-WTF 0.14.2, using a QuerySelectField, Flask-WTF raises "ValueError: too many values to unpack" in `wtforms/ext/sqlalchemy/fields.py` line 189, in `get_pk_from_identity`. It appears that SQLAlchemy 1.2 and later returns a third member from that call, and the library only expects two. Here's separate project's PR about the issue, and whose fix may be worth considering:
https://github.com/wtforms/wtforms-sqlalchemy/pull/10

I've put together a small Flask app demonstrating the bug here:
https://github.com/commandtab/flask-wtf-example

**Comment by davidism** [comment]
That's part of WTForms, not Flask-WTF.

**Comment by davidism** [comment]
@lepture what do you want to do here? WTForms isn't being updated, but I don't really want to pull this into Flask-WTF.

**Comment by commandtab** [comment]
@davidism Oh, silly me! I should have seen that it was an issue directly in WTForms.

What do you mean when you said WTForms isn’t being updated? Is the project no longer maintained?

Thanks!

**Comment by davidism** [comment]
I don't have access to make releases, only to merge stuff.

**Comment by commandtab** [comment]
Hmm. Should I open a similar issue or PR over in WTForms for someone to review and merge, then a project owner to release?

**Comment by davidism** [comment]
You can, I can review and merge it at some point when I have time.
