### ISSUE TITLE
breaks WTForms built-in I18N

### ISSUE THREAD

**Issue by slavkoja** [lepture/flask-wtf#333]
flask-wtf breaks WTForm's built-in localization. When i use WTForm's form, the translation works as expected, but the same form in ``flask-wtf`` is not translated (i omit all flask's stuff):
```python
from wtforms import Form
from flask_wtf import FlaskForm

class WForm(Form):
    class Meta:
        locales = ['sk', 'en']

class FForm(FlaskForm):
    class Meta:
        locales = ['sk', 'en']

wform = WForm()
fform = FForm()

print("wWTF:", wform.meta.get_translations(wform))
print("fWTF:", fform.meta.get_translations(fform))
```
the output is:
```
wWTF: <gettext.GNUTranslations object at 0x7f2b5ae5ba58>
fWTF: None
```
I was able to fix it by overriding the ``get_translations()`` method of ``Meta`` class:
```python
class FForm(FlaskForm):
    class Meta:
        locales = ['sk', 'en']
        
        def get_translations(self, form):
            return super(FlaskForm.Meta, self).get_translations(form)
```
Now i got:
```
wWTF: <gettext.GNUTranslations object at 0x7fe93ee88860>
fWTF: <gettext.GNUTranslations object at 0x7fe93ee88860>
```
But i am not sure, if it is proper solution.

regards

**Comment by greyli** [comment]
Check #316, you need to set `WTF_I18N_ENABLED` to `False` to enable locale setting.

**Comment by slavkoja** [comment]
I am sorry for delay.

I tried it already, it was cleared with other flask's stuff from previous code. But now i see that it is fixed in master, but i am on latest release  ``0.14.2``, anyway i will close it as known (and fixed) problem.

But please, consider to release this bugfix.

**Comment by neingeist** [comment]
I also hit this, please release a bugfix release :)
