### ISSUE TITLE
Form validate_on_submit() bug

### ISSUE THREAD

**Issue by linuxson27** [lepture/flask-wtf#334]
I am not sure if this is indeed a bug, just something weird I noticed today. I am using multiple forms in one of my routes, and so have multiple *.validate_on_submit() calls in succession. What I noticed was that if you don't implicitly include input validation (or perhaps any other kind would also work) per form, the first *.validate_on_submit() method gets called, whether intended or not. It does not 'select' the correct method when firing a form submit call. So are these calls blind? Or am I just not clued up enough on this topic...lol

**Comment by greyli** [comment]
`validate_on_submit()` doesn't detect which submit button was clicked, instead, it triggered as long as the request method is one of POST/DELETE/PATCH etc. See this [SO answer](https://stackoverflow.com/questions/18290142/multiple-forms-in-a-single-page-using-flask-and-wtforms/39766205#39766205) for more information.

**Comment by davidism** [comment]
Use the `prefix` argument to distinguish multiple forms on a single page.
