### ISSUE TITLE
Disabling CSRF check by default doesn't work for forms

### ISSUE THREAD

**Issue by james9909** [lepture/flask-wtf#336]
I noticed that setting `WTF_CSRF_CHECK_DEFAULT` doesn't won't work if the endpoint validates any `FlaskForm`. The CSRF token doesn't seem to be checked, but when I check the my logs, they say that `The CSRF token is missing`. Would it be possible to completely disable the CSRF check for forms if `WTF_CSRF_CHECK_DEFAULT` is set to false?

**Comment by greyli** [comment]
As the [docs](https://github.com/lepture/flask-wtf/blob/df423a96f05da4711d63549a379b366046dc2cc8/docs/config.rst#configuration) said, set `WTF_CSRF_ENABLED` to `False` to disable all CSRF protection.

**Comment by james9909** [comment]
Sorry, for not clarifying, but I want to conditionally enable CSRF for certain requests using the `@app.before_request` decorator. [The docs](https://github.com/lepture/flask-wtf/blob/master/docs/csrf.rst#exclude-views-from-protection) only say to set `WTF_CSRF_CHECK_DEFAULT` to false.

**Comment by james9909** [comment]
For example, adding an empty form to `tests/test_csrf_extension.py` and requiring it to validate causes `test_protect` to fail. I'm not sure if this is intended, but this behavior isn't mentioned from the docs and it kind of unintuitive.

**Comment by greyli** [comment]
Provide a minimal application may be helpful.

**Comment by james9909** [comment]
https://gist.github.com/james9909/ab1fe43c8322edee444c003df16d835a

**Comment by james9909** [comment]
Sorry, I didn't get any notifications about your comment on the gist, but I added some more info.

**Comment by greyli** [comment]
Since the problem was solved, could you close this issue?
