### ISSUE TITLE
CSRF token reuse

### ISSUE THREAD

**Issue by dmitrybelyakov** [lepture/flask-wtf#347]
Hi!

Was wondering why are CSRF tokens reused? We are using them in a single page app setup and a new token is generated on every request. However all of the previously generated tokens still work. It would be nice to drop the token from the session when a new one is being regenerated, or maybe have an option to `generate_csrf(force=True)`

**Comment by davidism** [comment]
CSRF tokens expire after `time_limit` seconds, which defaults to `WTF_CSRF_TIME_LIMIT` config, which defaults to 3600 (1 hour). You can lower this either globally or per-form with `Meta.csrf_time_limit`, but you need to account for how long you expect a user to take to fill out and submit a form.

If you'd like to make the tokens one time use (probably unnecessary, but I don't know the particulars of your application security needs), you can do the following:

```python
from flask_wtf import FlaskForm
from flask_wtf.csrf import _FlaskFormCSRF

class OneTimeCSRF(_FlaskFormCSRF):
    def validate_csrf_token(self, form, field):
        ...

class OneTimeForm(FlaskForm):
    class Meta:
        csrf_class = OneTimeCSRF

class ImportantForm(OneTimeForm):
    ...
```

**Comment by dmitrybelyakov** [comment]
Hi, thanks for looking into our issue. We found a workaround in the end. Cheers!
