### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Forever-Young** [lepture/flask-wtf#349]
According to https://stackoverflow.com/questions/44605393/object-of-type-bytes-is-not-json-serializable-when-upgrading-my-python-environ#comment81856742_44605645 that bug is fixed in master (and it is). Do you have plans to do a release?

**Comment by davidism** [comment]
Yes, we plan to make a new release.

The specific issue you're asking about appears to be a duplicate of #275, which does not require a new release.

**Comment by jeffoneill** [comment]
@davidism, it seems that fix in #275 requires all end users to delete cookies which is a really bad situation for production apps with lots of users.  

I really appreciate all your contributions and it would be great to get a new release of Flask-WTF when you or others have time.
