### ISSUE TITLE
[Docs] Dead link for essay against easy-install

### ISSUE THREAD

**Issue by Tadaboody** [lepture/flask-wtf#350]
In the [installation page](https://flask-wtf.readthedocs.io/en/stable/install.html#distribute-pip) the link detailing why you shouldn't use easy-install [is broken](https://python-packaging-user-guide.readthedocs.io/en/latest/pip_easy_install/)

**Comment by greyli** [comment]
This link was already removed in the master branch ([source](https://github.com/lepture/flask-wtf/blob/master/docs/install.rst)).
