### ISSUE TITLE
CSRF token in session

### ISSUE THREAD

**Issue by ozychhi** [lepture/flask-wtf#357]
Is there a good reason why https://github.com/lepture/flask-wtf/blob/9b029c379cfda2a7463cf771f933a1c425b4ce16/flask_wtf/csrf.py#L93 this check is being done? We are running multiple instances of flask behind alb and this is causing issues, we get occasional 400 `The CSRF session token is missing`. As far as I could understand we only set csrf_token for convenience.

**Comment by davidism** [comment]
Because CSRF protection requires matching a token in the session with a token in the form data. I can't say why your load balancer is occasionally dropping a user's session, but that sounds like an issue with your load balancer.

**Comment by slyang-git** [comment]
I have encountered the same problem. I am not using load balance.
