### ISSUE TITLE
Broken link in documentation for warning against easy_install

### ISSUE THREAD

**Issue by McEileen** [lepture/flask-wtf#360]
I was reading through the [documentation's instructions about installation this morning](https://flask-wtf.readthedocs.io/en/stable/install.html) and the link about easy_install, [shouldn't do that,](https://python-packaging-user-guide.readthedocs.io/en/latest/pip_easy_install/) is broken.

I can see that the broken link has already been addressed in a past [PR](https://github.com/lepture/flask-wtf/pull/122) and [issue](https://github.com/lepture/flask-wtf/issues/350) however, it remains up on the documentation.  Is there an estimate of when the link will be fixed in the documentation?  Thank you!

**Comment by davidism** [comment]
When we release a new version, new docs will be deployed.
