### ISSUE TITLE
BooleanField does not honor default value

### ISSUE THREAD

**Issue by ilons** [lepture/flask-wtf#362]
Hi.

I'm having issues with rendering a BooleanField correctly using flask-wtf 0.14.2 with wtforms 2.2.1.

In my form, I define the field as:
```
from flask_wtf import FlaskForm
from wtforms import BooleanField

class MyForm(FlaskForm):
    bool_field = BooleanField(label='My boolean', description='Should be cheked', default='checked')
```
But it renders unchecked like as `<input id="bool_field" name="bool_field" type="checkbox" value="y">`

However, if I instead use the render_kw it works:
```
class MyForm(FlaskForm):
    bool_field = BooleanField(label='My boolean', description='Should be cheked', render_kw={'checked': True})
```
Gives me: `<input checked="checked" id="bool_field" name="bool_field" type="checkbox" value="y">`

From reading the documentation on BooleanField for wtforms: https://wtforms.readthedocs.io/en/stable/fields.html#wtforms.fields.BooleanField it seems like the first approach (passing `default='checked'`) is indeed the proper way of doing it.

When I check the values directly from the form object using pure wtforms, it seems to work as expected:
```
import wtforms

class BooleanTest(wtforms.Form):
    field = wtforms.BooleanField(u'Boolean', default='checked')
form = BooleanTest()
```
Then form.field.data returns `True`, and it changes to `False` if I remove the `Default='checked'`.

What I expect is the first use case to return a checked checkbox, while id does not.
Am I doing something wrong, or do I miss something here?

**Comment by greyli** [comment]
Can't reproduce on my side, with given version and tested on Chrome / Firefox. 

I use your first example, it rendered as:
```html
<input checked class="form-check-input" id="bool_field" name="bool_field" type="checkbox" value="y">
```

**Comment by ilons** [comment]
I'll see if I can find time to create a complete example for this, in which case I'll re-open the issue.

**Comment by aadejare** [comment]
> Can't reproduce on my side, with given version and tested on Chrome and Firefox.
> 
> I use your first example, it rendered to:
> 
> ```
> <input checked class="form-check-input" id="bool_field" name="bool_field" type="checkbox" value="y">
> ```

That's the problem.  With HTML5 from what I've seen, you need another attribute "checked"  [see here where BooleanField is an input tag and will need the chceked parameter](https://www.w3schools.com/tags/att_input_checked.asp).
Until then, I would suggest adding the checked value yourself on load with Javascript or Jquery such as the following in Jquery:

`this.attr('checked', 'checked');`

**Comment by miettal** [comment]
I have same problem in flask-wtf 0.14.2, wtforms 2.2.1.

**Comment by mcescalante** [comment]
I also see this same issue in flask-wtf 0.14.2 and wtforms 2.2.1 with Flask 1.1.1. My setup is reasonably complex so it could be something else, but replacing `FlaskForm` with `wtform.Form` makes `default="checked"` work properly and set the default checkbox to checked.

**Comment by iskyd** [comment]
Same issue with flask-wtf 0.14.2 and wtforms 2.2.1
