### ISSUE TITLE
csrf_token is always valid unless it its expiry？

### ISSUE THREAD

**Issue by stonePJ** [lepture/flask-wtf#366]
I use `form.validate_on_submit()` to verify the csrf_token and successfully return the result. When I repeat send the request packet with the same csrf_token, server return the same result. It means the csrf_token is not disposable.

**Comment by stonePJ** [comment]
![image](https://user-images.githubusercontent.com/26664765/56120359-8c042a00-5fa0-11e9-8486-ba41f8c33178.png)
After more than 6 min, it still valid.
![image](https://user-images.githubusercontent.com/26664765/56120434-aa6a2580-5fa0-11e9-8e39-e0dfbd70ded1.png)

**Comment by davidism** [comment]
Because otherwise, any navigation or interaction outside of one form at a time doesn't work.
