### ISSUE TITLE
Implicit formdata processing might not be a good idea

### ISSUE THREAD

**Issue by torotil** [lepture/flask-wtf#368]
### Problem

In some circumstances you might want to change a form’s configuration after the form object was instantiated. Consider the following example:

```python

class MyForm(FlaskForm):
    choose = SelectField()

def my_view():
    form = MyForm()
    form.choose.choices = generate_choices_at_runtime()
    if form.validate_on_submit():
         # do something
```

This will work fine during the GET request to `my_view` but it will fail in the POST request as `choose.choices` is not populated at the time the form input is handled.

The problem is that [`FlaskForm.__init__()`](https://github.com/lepture/flask-wtf/blob/9b029c379cfda2a7463cf771f933a1c425b4ce16/flask_wtf/form.py#L76) implicitly triggers input processing.

### Proposed solution

While I think it is a good idea to have some way to automatically process form input from `flask.request` it might be better to trigger this not before `validate_on_submit()`. I’d suggest the following changes:

1. Introduce a new method (ie. `FlaskForm.process_request_data()`) that reads the form data from the `request` and runs `process()` if appropriate. Make it so that the method is only executed once even if it is called multiple times.
2. Call this new method at the beginning of `validate_on_submit()`.

This way pure declarative forms continue to work without changes, while a non-obvious pitfall for advanced use-cases is avoided.

**Comment by davidism** [comment]
When data is processed is a behavior of wtforms, not flask-wtf.

Dynamic configuration should be done by overriding the init method of the form, not after the fact.

**Comment by torotil** [comment]
> When data is processed is a behavior of wtforms, not flask-wtf.

When the data is passed is a behaviour of flask-wtf. See the linked code.

> Dynamic configuration should be done by overriding the init method of the form, not after the fact.

Can you point me to the point in the wtforms documentation where this is stated?

**Comment by torotil** [comment]
It seems that my problem is a bit more specific as it involves wtforms-alchemy and nested `ModelForms`. So my example might be overly simplified. In my case it’s not possible to make the modifications on the unbound fields.

The point still stands: If I don’t pass data explicitly to the constructor I don’t expect any processing on input data to occur before the call to `form.validate_on_submit()`.
