### ISSUE TITLE
reCaptcha not working under Safari 12.1.1 when widget is loaded in iframe

### ISSUE THREAD

**Issue by Reve** [lepture/flask-wtf#369]
reCaptcha not working under Safari 12.1.1 when widget is loaded in iframe. When you select an image, the whole reCaptcha window turns white (see picture).

Steps to reproduce:
- insert reCaptcha field inside iframe
- try to solve captcha

<img width="912" alt="Screenshot 2019-06-10 at 13 02 58" src="https://user-images.githubusercontent.com/735340/59188528-84b46380-8b80-11e9-83f9-7d71a330b78f.png">

**Comment by davidism** [comment]
That would be an issue with reCaptcha, not with Flask-WTF.
