### ISSUE TITLE
0.15 release ?

### ISSUE THREAD

**Issue by tomotaka** [lepture/flask-wtf#374]
I want 0.15 release to solve this issue:
https://stackoverflow.com/questions/44605393/object-of-type-bytes-is-not-json-serializable-when-upgrading-my-python-environ

This problem seems to be solved by this commit:
https://github.com/lepture/flask-wtf/commit/eff54eca0d0c070a32da8815f9efd5189add3f1e

Could you please just release v0.15 to PyPI ?
Thanks.

**Comment by meekrosoft** [comment]
Can I ask why this this is closed?  Can I help to make this release?

**Comment by tomotaka** [comment]
I don't know why this issue is closed.

Here is my workaround:

put this line into requirements.txt:

```
git+https://github.com/lepture/flask-wtf.git@9b029c379cfda2a7463cf771f933a1c425b4ce16#egg=Flask_WTF
```

**Comment by meekrosoft** [comment]
Thanks a lot!
