### ISSUE TITLE
DeprecationWarning: The import 'werkzeug.url_encode' is deprecated 

### ISSUE THREAD

**Issue by nblock** [lepture/flask-wtf#377]
Pytest displays the following deprecation warning:
```
.tox/py37/lib/python3.7/site-packages/flask_wtf/recaptcha/widgets.py:5: DeprecationWarning: The import 'werkzeug.url_encode' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.urls import url_encode' instead.
    from werkzeug import url_encode
```

Versions:
* Python: 3.7.4
* pytest: 5.1.2
* Flask-WTF: 0.14.2

**Comment by atzannes** [comment]
I started seeing the same warning when I upgraded my `werkzeug` dependency version from 0.15.6 to 0.16.0

**Comment by meekrosoft** [comment]
Hi there,
I'm super happy that this has been fixed.  Will there be a new release to include the update?
Thanks for your work!
Best regards,
Mike

**Comment by postmasters** [comment]
0.14.3 contains pr #378, which fixed this deprecation.
