### ISSUE TITLE
Date field not working in Safari

### ISSUE THREAD

**Issue by rickwierenga** [lepture/flask-wtf#379]
Form:

```python
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm
from wtforms.fields.html5 import DateField

class BookingForm(FlaskForm):
    date = DateField('Date', format='%Y-%m-%d', validators=[DataRequired()], render_kw={"placeholder": "yyyy/mm/dd"})
```

HTML:
```html
{{ form.date(class="form-control form-control-lg") }}
```

This works fine in Chrome but it doesn't even validate in Safari: https://imgur.com/a/hX0t25A.

**Comment by davidism** [comment]
It's not supported by Safari, WTForms has no control over that (and Flask-WTF is only a wrapper around WTForms). https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by rickwierenga** [comment]
For future people, there is a library Bootstrap-Datepicker that is supported in Safari. [Docs](https://bootstrap-datepicker.readthedocs.io)
