### ISSUE TITLE
CSRF session token is missing issue

### ISSUE THREAD

**Issue by rbcabreraUPM** [lepture/flask-wtf#380]
I keep encountering this error per request after following the document about using Javascript to set the csrf token in the header

Please provide how to fix this issue when using Fetch API

**Comment by Craicerjack** [comment]
Having the same issue. 
Thought it might be similar to #284  but the solution is there. Its weird because the csrf_token is in the headers.

![Screenshot from 2020-03-03 13-11-13](https://user-images.githubusercontent.com/4867797/75778856-80545a00-5d50-11ea-93cb-0b1caf2ea9f8.png)  

```
fetch(event.target.action, {
    method: 'POST',
    headers: { 
      "Content-Type": "multipart/form-data",
      "X-CSRFToken": csrf_token,
    },
    credentials: "same-origin",
    body: formData,
  })
```

**Comment by rbcabreraUPM** [comment]
this works! thanks!
