### ISSUE TITLE
CSRF security improvements

### ISSUE THREAD

**Issue by Dreamsorcerer** [lepture/flask-wtf#385]
It doesn't look like the CSRF token is using best practices for security, which may be important for a high-security website. Suggestions for improvement:

1. Replace `hashlib.sha1(os.urandom(64)).hexdigest()` with `secrets.token_hex()`. This provides a more secure token (and defaults to a secure number of bytes, so no need to maintain it). Perhaps use the old code as a fallback mechanism for Python <3.6.

2. The salt is set to the hard-coded value: 'wtf-csrf-token'. A publically known value used across hundreds of websites rather defeats the point of a salt. There should really be a setting to define the salt for each application (and the documentation should recommend setting it to a random value).

3. For a defense-in-depth approach, it might be nice to have an option to disable verification of the token in field/POST data, and instead require verification to be done via the HTTP header in JS requests. Reasoning is that the browser will block requests that set custom headers from another site (2nd paragraph after bullet points):
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#synchronizer-token-pattern

**Comment by davidism** [comment]
Thanks for the suggestions. The CSRF token is relying on itsdangerous to provide the security for the token. The token is cryptographically signed with your app's secret key (or a separate key configured for CSRF). In itsdangerous, the `salt` parameter is somewhat misnamed, and is not intended as a salt for defeating cracking. I'm not clear what you're trying to describe with 3, but you can already enable the extension version of CSRF protection, which looks at a header or form value for the token.

**Comment by Dreamsorcerer** [comment]
For 1, I'm still suspicious. The security surely depends on not being able to find the same token regardless of encrypting through itsdangerous. If that were not the case, you would just set the token to 1 or something.
If an attacker can get the user to send multiple requests, they can do so with multiple tokens they've retrieved from the website. If any of them match the user's current token, then the attack succeeds. My suggestion just helps ensure that can't happen.

2: I see that the 'salt' appears to actually help avoid collisions between different applications or something, so I agree that's not an issue.

For 3, I'm saying that if an attacking website is able to figure out the token, they can only send the token via form/POST data. They are unable to send it via an HTTP header. Therefore, disabling the option to accept the token via form/POST data, adds an extra layer of security (this obviously requires all forms to be submitted via JS). (That page actually says that some sites can just check for the presence of a given HTTP header without a token or any other anti-CSRF methods, as a quick and easy method).
