### ISSUE TITLE
new werkzeug lib break import typo

### ISSUE THREAD

**Issue by jerome-diver** [lepture/flask-wtf#396]
new version of werkeug python library (from 1.0.0) need to import own libs differently:
```
from werkzeug.datastructures import ImmutableDict
from werkzeug.urls import ulr_open
```
this does impact almost two of your files:

- recaptcha/validators.py
- recaptcha/widgets.py

**Comment by davidism** [comment]
Flask-WTF 0.14.3 is compatible with Werkzeug 1.0.0. I'm not sure where you're seeing the typo, but that's not in the current code either.

**Comment by jerome-diver** [comment]
from archlinux community repo:
community/python-flask-wtf 0.14.2-5
Maybe it was not at this version of flask-wtf...
