### ISSUE TITLE
Activate weekly builds for Travis

### ISSUE THREAD

**Issue by jugmac00** [lepture/flask-wtf#406]
Currently, it seems that builds are only triggered on a push - but not regularly. This means that e.g. Python updates or updates of direct or transitive dependencies could cause problems and get unnoticed for a longer time than necessary.

**Comment by davidism** [comment]
This won't help me, as I don't receive emails on failures, and enabling emails would not be effective given my workload. If new support needs to be added or removed, I'm always happy to review PRs as I can get to them.
