### ISSUE TITLE
ImportError: cannot import name 'HTMLString' from 'wtforms.widgets'

### ISSUE THREAD

**Issue by Mukvin** [lepture/flask-wtf#408]
WTFS was upgraded in today, 2020/04/22,zh.
![image](https://user-images.githubusercontent.com/34978943/79938098-39e8c500-848e-11ea-9364-cb5e0e4a9ca6.png)
When I init env, then the importError was happended.
So If you wanted to workround, just set the version of WTForms to be lower 2.3.0

**Comment by davidism** [comment]
WTForms 2.3.1 is released that adds this back. Still need to change Flask-WTF since the imports are deprecated.
