### ISSUE TITLE
FieldList fails validation because raw_data was not set

### ISSUE THREAD

**Issue by PDiracDelta** [lepture/flask-wtf#413]
My full form structure is:
`myForm: FieldList: FormField: mySubForm: FieldList: BooleanField`
The first FieldList fails validation (`InputRequired`, which checks `.raw_data`) because its `.raw_data` attribute was not set, even though its `.data` was set!

I don't fiddle with the form data after submission, so I suppose this is a bug?

**Comment by davidism** [comment]
If this was a bug, it would be with WTForms, not Flask-WTF. However, this is just a weird validation case. InputRequired works with direct fields, not higher order fields like FieldList. You'll want to write your own validators for those most of the time.
