### ISSUE TITLE
Stop support for python2

### ISSUE THREAD

**Issue by zhukewen1998** [lepture/flask-wtf#426]
Happens when running 'python setup.py install'

byte-compiling build/bdist.linux-x86_64/egg/flask_wtf/csrf.py to csrf.pyc
  File "build/bdist.linux-x86_64/egg/flask_wtf/csrf.py", line 220
    dest = f'{view.__module__}.{view.__name__}'
                                              ^
SyntaxError: invalid syntax

**Comment by davidism** [comment]
The next version, as demonstrated by the error you've shown, does not support Python 2.
