### ISSUE TITLE
How to prevent against login CSRF attacks?

### ISSUE THREAD

**Issue by k-time** [lepture/flask-wtf#430]
Apologies if this isn't the right place to bring this up, if there's a better place then please let me know.

Initially I thought it wasn't necessary to add CSRF protection to my login page. However I'm reading that login CSRF attacks do actually exist:

https://stackoverflow.com/a/15350123/7614293
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#login-csrf

Is it sufficient to just use a FlaskForm as normal on the login page? [This](https://stackoverflow.com/questions/6412813/do-login-forms-need-tokens-against-csrf-attacks/15350123#15350123) answer says that

>Login CSRF can be mitigated by creating pre-sessions (sessions before a user is authenticated) and including tokens in login form.

but 

>Remember that pre-sessions cannot be transitioned to real sessions once the user is authenticated - the session should be destroyed and a new one should be made

so I'm not quite sure. Using a FlaskForm on my login page, I've been getting a "CSRF token has expired" error where I need to refresh and login again for the login to succeed. I'm not sure what the root cause is, but it leads me to believe that I can't use flask-wtf's CSRF protection on a logged-out route like the login page.

Thanks for any help.

**Comment by davidism** [comment]
Yes, using FlaskForm is fine.
