### ISSUE TITLE
Problem with importing wtforms inside html5.py file

### ISSUE THREAD

**Issue by lcmen** [lepture/flask-wtf#46]
I'm doing blog application to learn Python and Flask and I would like to launch it on Google App Engine. Unfortunately I have small problem with importing WTForms to the application. I'm currently using Flask 0.9, WTForms 1.0.1 and Flask-WTForms 0.8. I've added flaskext_wtf folder to root path of my project but I'm getting error from html5.py file.

[code]
File "/Users/lucas/Workspace/blog/flask_wtf/html5.py", line 1, in <module>
from wtforms import TextField
File "/Users/lucas/Workspace/blog/flask/exthook.py", line 86, in load_module
raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.wtf.wtforms
It looks like it tries to find wtforms inside the extension path instead of my project path. How can I inform the html5.py file to look for the wtforms in the root?[/code]

Here are sources of my project - https://bitbucket.org/lucas_mendelowski/wblog/src

**Comment by moovon** [comment]
Even after changing different import styles and re-installing flask, flask-wtf, if it still does not works : then in the config.py("config.py may be of different name eg app_config.py etc)

insert the line

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 
'venv/Lib/site-packages'))

set the lib path of your own app , in my case it was "venv/Lib/site-packages"
